version: '3.1'

services:

  postgres:
    container_name: treedb
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_DB: treedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
